version: 2.1
jobs:
  build-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/
  upload-rhel7:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo yum -y install dnf
            sudo dnf -y install python3-pip
            pip3 install awscli --upgrade --user
      - run:
          name: Sync artifacts to S3
          command: |
            export PATH=$PATH:~/.local/bin
            aws s3 cp /dist s3://fmi-smartmet-cicd-beta/centos7/ --recursive
  build-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/
  upload-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-7:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo yum -y install dnf
            sudo dnf -y install python3-pip
            pip3 install awscli --upgrade --user
      - run:
          name: Sync artifacts to S3
          command: |
            export PATH=$PATH:~/.local/bin
            aws s3 cp /dist s3://fmi-smartmet-cicd-beta/centos9/ --recursive

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel7
      - build-rhel9
      - test-rhel7:
          requires:
            - build-rhel7
      - test-rhel9:
          requires:
            - build-rhel9
      - upload-rhel7:
          context: fmi-global
          requires:
            - test-rhel7
      - upload-rhel9:
          context: fmi-global
          requires:
            - test-rhel9