version: 2.1
jobs:
  build-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/
  upload-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo yum -y install dnf
            sudo dnf -y install python3-pip
            pip3 install awscli --upgrade --user
      - run:
          name: Sync artifacts to S3
          command: |
            export PATH=$PATH:~/.local/bin
            aws s3 cp /dist s3://fmi-smartmet-cicd-beta/centos8/ --recursive
  build-rhel10:
    docker:
      - image: quay.io/fmi/smartmet-cibase-10:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - persist_to_workspace:
          root: /dist
          paths: ./*.rpm
  test-rhel10:
    docker:
      - image: quay.io/fmi/smartmet-cibase-10:latest
    resource_class: xlarge
    environment:
      RPM_BUILD_NCPUS: 8
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
      - store_artifacts:
          path: /dist
          destination: dist/
  upload-rhel10:
    docker:
      # No need to use smartmet-cibase-10
      - image: fmidev/smartmet-cibase-8:latest
    steps:
      - attach_workspace:
          at: /dist
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo yum -y install dnf
            sudo dnf -y install python3-pip
            pip3 install awscli --upgrade --user
      - run:
          name: Sync artifacts to S3
          command: |
            export PATH=$PATH:~/.local/bin
            aws s3 cp /dist s3://fmi-smartmet-cicd-beta/centos10/ --recursive
workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel8
      - test-rhel8:
          requires:
            - build-rhel8
      - upload-rhel8:
          context: fmi-global
          requires:
            - test-rhel8
      - build-rhel10
      - test-rhel10:
          requires:
            - build-rhel10
      - upload-rhel10:
          context: fmi-global
          requires:
            - test-rhel10
