# This file is used to run manual tests locally
#
# Command (rhel8 tapauksessa):
#   circleci local execute --config .circleci/manual.yml test-rhel8
#
version: 2.1
jobs:
  test-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
  test-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
  test-rhel10:
    docker:
      - image: quay.io/fmi/smartmet-cibase-10:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: ci-build deps
      - run:
          name: Build RPM
          command: ci-build rpm
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y /dist/*.rpm
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
workflows:
  version: 2.1
  build:
    jobs:
      - test-rhel8
      - test-rhel9
      - test-rhel10
